name: CI22

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: commit-list-action
        uses: sidorovpavel/branches-difference-action@main
        with:
          github-token: ${{secrets.TOKEN}}
          project-name: 'MM'
          branch-compare: 'main'
          branch-comapre: 'test'
          pull-number: '3'

