name: Realise for pull request

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set var
        env:
          FIRST_NAME: Mona
          LAST_NAME: Octocat

      - name: get commits list
        uses: actions/github-script@v4
        id: commits-list
        with:
          github-token: ${{secrets.TOKEN}}
          script: |
            const commits = await github.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            const jira_matcher = /\d+-[A-Z]+(?!-?[a-zA-Z]{1,10})/g;
            const issues = commits.data.reduce((issues, item) => {
              const names = item.commit.message.split("").reverse().join("").match(jira_matcher);
              if (!names) {
                return issues;
              }
              names.forEach(res => {
                const id = res.split("").reverse().join("");
                if(issues.indexOf(id)===-1) {
                  issues.push(id)
                }
              })
              return issues;
            }, []);
            return JSON.stringify(issues);
          result-encoding: string
      - name: set version
        uses: actions/github-script@v4
        id: jira-version-set
        with:
          jira-token: ${{secrets.JIRA_TOKEN}}
          jira-user: ${{secrets.JIRA_USER}}
          jira-domain: 'tangem'
          release-version: 'test'
          project-name: 'MM'
          issues: ${{steps.commits-list.outputs.result}}
          script: |
            console.log(`Hello ${FIRST_NAME} ${LAST_NAME}`);


