name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context);

      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # - run: npm ci
      # - run: npm install moment
      # - run: npm install node-fetch

      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.TOKEN}}
          script: |

            console.log(context);
