name: CI22test-jira

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: commit-list-action
        id: commit-list-action
        uses: sidorovpavel/branches-difference-action@main
        with:
          github-token: ${{secrets.TOKEN}}
          base: 'main'
          head: 'test'
          pull-number: '1'

      - name: Get the output time
        run: echo "The time was ${{ steps.commit-list-action.outputs.issues }}"
        
      - name: Jira Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          

          
      - name: Jira Action 5
        id: branch
        uses: sidorovpavel/jira-version-action@main
        with:
          action: getBranchSummary  
          branch-name: JS-45_trataa         

      - name: Get the output time2
        run: echo "The time was ${{ steps.branch.outputs.result }}"
        
      - name: Jira Action 6
        id: branch2
        uses: sidorovpavel/jira-version-action@main
        with:
          action: getBranchId
          branch-name: JS-45_trataa         

      - name: Get the output time2
        run: echo "The time was ${{ steps.branch2.outputs.result }}"
        
