name: CI-jira

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the output time
        run: echo "The time was ${{ steps.commit-list-action.outputs.issues }}"
        
      - name: Jira Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          
          
      - name: Jira Action 5
        id: branch
        uses: tangem/jira-action@JS-106
        with:
          action: getBranchSummary  
          branch-name: JS-45_trataa     
          
      - name: Jira Check Version
        id: jira-check-version
        uses: tangem/jira-action@master
        with:
          action: checkVersion
          project: IOS
          version: test
          
      - name: Jira Check Version Log
        run: echo "The key was ${{ steps.jira-check-version.outputs.result }}"     

      - name: Jira Create Version
        id: jira-create-version
        uses: tangem/jira-action@master
        with:
          action: createVersion
          project: IOS
          version: test     
        
          
      - name: Jira create Version Log
        run: echo "The key was ${{ steps.jira-create-version.outputs.result }}" 
      
      
      - name: Get the output time3
        run: echo "The summary was ${{ steps.branch.outputs.summary }}"
        
      - name: Get the output time4
        run: echo "The key was ${{ steps.branch.outputs }}"  
        
        
      - name: Get the output time5
        run: echo "The key was ${{ steps.branch.outputs.result }}"
        
