name: CI22test

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: commit-list-action
        uses: sidorovpavel/branches-difference-action@main
        with:
          github-token: ${{secrets.TOKEN}}
          project-name: 'MM'
          base: 'main'
          head: 'test'
          pull-number: '1'

      - name: Get the output time
        run: echo "The time was ${{ steps.commit-list-action.outputs.issues }}"
