name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: commit-list-action
        uses: ./.github/actions/commit-list
        with:
          repo-token: ${{secrets.TOKEN}}
          jira-token: ${{secrets.JIRA_TOKEN}}
          jira-user: ${{secrets.JIRA_USER}}
          jira-domain: 'tangem'
          release-version: 'test2'
          project-name: 'MM'
